name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
      sha: ${{ steps.release.outputs.sha }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # Use a personal access token to trigger subsequent workflows
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          # Use simple release type for Docker projects
          release-type: simple
          # Target the main branch
          target-branch: main
          # Configuration files
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  # This job runs after a release is created to update container tags
  update-container-tags:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          event-type: release-created
          client-payload: |
            {
              "tag_name": "${{ needs.release-please.outputs.tag_name }}",
              "version": "${{ needs.release-please.outputs.version }}",
              "sha": "${{ needs.release-please.outputs.sha }}"
            }